const productsList = [
  {
    id_product: 1,
    category: "vestidos_casuais",
    fk_idcategorys: 1,
    name_product: "Faux Suede Mini Skirt",
    description_product: "A faux suede mini skirt featuring exposed button-front closures and panel seam construction.",
    price: 500,
    image: "./desafio-maeztra-javascript/images/produtos/faux_suede_mini _skirt.png",
    id_categorys: 1,
    name_categorys: "Vestidos Casuais",
    selected: false,
    option: ['#DEAC71', '#D37164', '#6497D3', '#3C3B79']
  },
  {
    id_product: 2,
    category: "vestidos_floral",
    fk_idcategorys: 2,
    name_product: "Ruched Rose Print Mini Skirt",
    description_product: "A satin mini skirt featuring an allover floral print, ruched side with self-tie closure, concealed back zipper, and a flounce hem.",
    price: 320,
    image: "./desafio-maeztra-javascript/images/produtos/ruched_rose_print_mini_skirt.png",
    id_categorys: 2,
    name_categorys: "Vestidos Florais",
    selected: false,
    option: ['#353535', '#D84E4B', '#CFC9B0', '#EAE9E5']
  },
  {
    id_product: 9,
    category: "vestidos_casuais",
    fk_idcategorys: 1,
    name_product: "Faux Suede Mini Skirt",
    description_product: "A faux suede mini skirt featuring exposed button-front closures and panel seam construction.",
    price: 500,
    image: "./desafio-maeztra-javascript/images/produtos/faux_suede_mini _skirt.png",
    id_categorys: 1,
    name_categorys: "Vestidos Casuais",
    selected: false,
    option: ['#DEAC71', '#D37164', '#6497D3', '#3C3B79']
  },
  {
    id_product: 4,
    category: "vestidos_floral",
    fk_idcategorys: 2,
    name_product: "Ruched Rose Print Mini Skirt",
    description_product: "A satin mini skirt featuring an allover floral print, ruched side with self-tie closure, concealed back zipper, and a flounce hem.",
    price: 320,
    image: "./desafio-maeztra-javascript/images/produtos/ruched_rose_print_mini_skirt.png",
    id_categorys: 2,
    name_categorys: "Vestidos Florais",
    selected: false,
    option: ['#353535', '#D84E4B', '#CFC9B0', '#EAE9E5']
  },
  {
    id_product: 10,
    category: "vestidos_casuais",
    fk_idcategorys: 1,
    name_product: "Faux Suede Mini Skirt",
    description_product: "A faux suede mini skirt featuring exposed button-front closures and panel seam construction.",
    price: 500,
    image: "./desafio-maeztra-javascript/images/produtos/faux_suede_mini _skirt.png",
    id_categorys: 1,
    name_categorys: "Vestidos Casuais",
    selected: false,
    option: ['#DEAC71', '#D37164', '#6497D3', '#3C3B79']
  },
  {
    id_product: 11,
    category: "vestidos_floral",
    fk_idcategorys: 2,
    name_product: "Ruched Rose Print Mini Skirt",
    description_product: "A satin mini skirt featuring an allover floral print, ruched side with self-tie closure, concealed back zipper, and a flounce hem.",
    price: 320,
    image: "./desafio-maeztra-javascript/images/produtos/ruched_rose_print_mini_skirt.png",
    id_categorys: 2,
    name_categorys: "Vestidos Florais",
    selected: false,
    option: ['#353535', '#D84E4B', '#CFC9B0', '#EAE9E5']
  },
  {
    id_product: 6,
    category: "vestidos_casuais",
    fk_idcategorys: 1,
    name_product: "Faux Suede Mini Skirt",
    description_product: "A faux suede mini skirt featuring exposed button-front closures and panel seam construction.",
    price: 500,
    image: "./desafio-maeztra-javascript/images/produtos/faux_suede_mini _skirt.png",
    id_categorys: 1,
    name_categorys: "Vestidos Casuais",
    selected: false,
    option: ['#DEAC71', '#D37164', '#6497D3', '#3C3B79']
  },
  {
    id_product: 7,
    category: "vestidos_floral",
    fk_idcategorys: 2,
    name_product: "Ruched Rose Print Mini Skirt",
    description_product: "A satin mini skirt featuring an allover floral print, ruched side with self-tie closure, concealed back zipper, and a flounce hem.",
    price: 320,
    image: "./desafio-maeztra-javascript/images/produtos/ruched_rose_print_mini_skirt.png",
    id_categorys: 2,
    name_categorys: "Vestidos Florais",
    selected: false,
    option: ['#353535', '#D84E4B', '#CFC9B0', '#EAE9E5']
  },
  {
    id_product: 3,
    category: "vestidos_casuais",
    fk_idcategorys: 1,
    name_product: "Faux Suede Mini Skirt",
    description_product: "A faux suede mini skirt featuring exposed button-front closures and panel seam construction.",
    price: 500,
    image: "./desafio-maeztra-javascript/images/produtos/faux_suede_mini _skirt.png",
    id_categorys: 1,
    name_categorys: "Vestidos Casuais",
    selected: false,
    option: ['#DEAC71', '#D37164', '#6497D3', '#3C3B79']
  },
  {
    id_product: 5,
    category: "vestidos_floral",
    fk_idcategorys: 2,
    name_product: "Ruched Rose Print Mini Skirt",
    description_product: "A satin mini skirt featuring an allover floral print, ruched side with self-tie closure, concealed back zipper, and a flounce hem.",
    price: 320,
    image: "./desafio-maeztra-javascript/images/produtos/ruched_rose_print_mini_skirt.png",
    id_categorys: 2,
    name_categorys: "Vestidos Florais",
    selected: false,
    option: ['#353535', '#D84E4B', '#CFC9B0', '#EAE9E5']
  },
  {
    id_product: 8,
    category: "vestidos_casuais",
    fk_idcategorys: 1,
    name_product: "Faux Suede Mini Skirt",
    description_product: "A faux suede mini skirt featuring exposed button-front closures and panel seam construction.",
    price: 500,
    image: "./desafio-maeztra-javascript/images/produtos/faux_suede_mini _skirt.png",
    id_categorys: 1,
    name_categorys: "Vestidos Casuais",
    selected: false,
    option: ['#DEAC71', '#D37164', '#6497D3', '#3C3B79']
  },
  {
    id_product: 12,
    category: "vestidos_floral",
    fk_idcategorys: 2,
    name_product: "Ruched Rose Print Mini Skirt",
    description_product: "A satin mini skirt featuring an allover floral print, ruched side with self-tie closure, concealed back zipper, and a flounce hem.",
    price: 320,
    image: "./desafio-maeztra-javascript/images/produtos/ruched_rose_print_mini_skirt.png",
    id_categorys: 2,
    name_categorys: "Vestidos Florais",
    selected: false,
    option: ['#353535', '#D84E4B', '#CFC9B0', '#EAE9E5']
  },
];

export default productsList;
